name: Sync labels

on:
  push:
    paths:
      - ".github/labels.yml"

jobs:
  labels:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          config-file: .github/labels.yml

          # If you want to delete any additional label, set this to true
          delete-other-labels: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.GITHUB_TOKEN }}